name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Detecta se é um projeto Node (tem package.json)
      - name: Detect project type
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "node=true" >> $GITHUB_OUTPUT
          else
            echo "node=false" >> $GITHUB_OUTPUT
          fi

      # Só configura Node se existir package.json
      - name: Setup Node
        if: steps.detect.outputs.node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (optional)
        if: steps.detect.outputs.node == 'true'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (optional)
        if: steps.detect.outputs.node == 'true'
        run: npm run lint --if-present

      - name: Test (optional)
        if: steps.detect.outputs.node == 'true'
        run: npm test --if-present

      - name: Build (optional)
        if: steps.detect.outputs.node == 'true'
        run: npm run build --if-present
