name: Super Linter

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false   # sรณ checa arquivos alterados no PR/push
          MARKDOWN_CONFIG_FILE: .markdownlint.jsonc
          YAML_CONFIG_FILE: .yamllint
